# Generated by Django 5.0.1 on 2024-09-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_alter_userlogin_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='is_block',
            new_name='is_blocked',
        ),
    ]
