# Generated by Django 5.0.1 on 2024-09-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_alter_userlogin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={},
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='last_login',
        ),
    ]
