# Generated by Django 5.0.1 on 2024-09-19 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_alter_userlogin_options_remove_userlogin_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='userlogin',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
